version: '3'

services:
  web:
    build: .
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: mysql:5.7.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: database
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: