version: '3'

services:
  web:
    build: .
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: hypriot/rpi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: database
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: